### ISSUE TITLE
Error installing with latest mecab version

### ISSUE THREAD

**Issue by markburns** [markburns/mecab#2]
```
>> require 'mecab'
=> true
>>
?>   sentence = "太郎はこの本を二郎を見た女性に渡した。"
=> "太郎はこの本を二郎を見た女性に渡した。"
>> tagger = MeCab::Tagger.new
dyld: lazy symbol binding failed: Symbol not found: __ZN5MeCab12getLastErrorEv
  Referenced from: /Users/markburns/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/mecab-0.996/mecab.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN5MeCab12getLastErrorEv
  Referenced from: /Users/markburns/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/mecab-0.996/mecab.bundle
  Expected in: flat namespace

[1]    14378 trace trap  irb
```

@keichan34 - any ideas?

**Comment by keichan34** [comment]
Ah, I see. It seems like it's working with 2.1.2, but not 2.1.0 (or 2.0.0 / 1.9.3 for that matter). I'll look into it in a bit, sorry about that.

**Comment by markburns** [comment]
No need to apologize. Thanks for the pull request. OK I'll try 2.1.2.
Although it would be nice to follow the versioning of the mecab library itself, I can imagine it becoming difficult. Basically we can't make any mistakes whatsoever, or have to append some extra digits after the mecab version or something.

I'm prepared to change the gem versioning and/or release a version that will work for a specified ruby version though if we need to.

**Comment by markburns** [comment]
Looks like this is related: http://d.hatena.ne.jp/kasei_san/20121213/p1

**Comment by markburns** [comment]
Get this on ruby 2.1.2

```
>> require 'mecab' #=> true
>>
 >   sentence = "太郎はこの本を二郎を見た女性に渡した。"
>> tagger = MeCab::Tagger.new
RuntimeError:
    from (irb):4:in `initialize'
    from (irb):4:in `new'
    from (irb):4
    from /Users/markburns/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
>> puts tagger.parse sentence
NoMethodError: undefined method `parse' for nil:NilClass
    from (irb):5
    from /Users/markburns/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

**Comment by markburns** [comment]
Closing this, any further discussion can continue on #3
